public enum PopupId
{
    [UnityEngine.HideInInspector] None = 0,
    Cheat = 1,
    Pause = 2,
    Win = 3,
    Revive = 4,
    Retry = 5,
    Spin = 6,
    SpinReward = 7,
    Settings = 8,
    JourneyGift = 9,
    DailyReward = 11,
    Challenge = 12,
    RemoveAds = 13,
    NoInternet = 14,
    TrophyLeague1 = 15,
    TrophyLeague2 = 16,
    Shop = 17,
    FreeChestReward = 18,
    PurchaseFailed = 19,
    PurchaseSuccess = 20,
    WinTrophyLeague = 21,
    TrophyLeague3 = 22,
    TrophyMultiplier = 23,
    Win1 = 24,
    DailyQuest = 25,
    DailyQuestExtra = 26,
    DailyQuestReward = 27,
    LevelRace = 28,
}
